### ISSUE TITLE
Windows wheel in PyPI

### ISSUE THREAD

**Issue by andreafioraldi** [angr/pyvex#102]
Hi,
can you add a Windows wheel in PyPI?
Thanks :)

**Comment by rhelmot** [comment]
We have had windows wheels in the past, and there's nothing stopping us from having them again! Except that I haven't booted my windows machine in like a month and I'm typing this from my phone which should be an indicator that I'm way too busy to deal with distribution right now

@ltfish can you do this please, for i386 and then x86_64? There are some scripts in angr-dev/admin that try to do it in an automated fashion but I don't think any of them work. It should just come down to `python setup.py bdist_wheel` though. Also if you can build unicorn/capstone wheels I can upload those too but those are super god damn complicated.

**Comment by rhelmot** [comment]
(we should probably make a release first if we're going to push new code to pypi)

**Comment by ltfish** [comment]
> we should probably make a release first if we're going to push new code to pypi

Let's make a release tomorrow then.

> Also if you can build unicorn/capstone wheels I can upload those too but those are super god damn complicated.

Yes please...
