### ISSUE TITLE
ReadError exception in GymratLifter

### ISSUE THREAD

**Issue by ArtemShypotilov** [angr/pyvex#116]
Hi Guys!

I've been using gymrat lifter recently and came into exception:

```
  File "/usr/local/lib/python2.7/dist-packages/angr/analyses/cfg/cfg_fast.py", line 3376, in _generate_cfgnode
    irsb = lifted_block.vex
  File "/usr/local/lib/python2.7/dist-packages/angr/block.py", line 145, in vex
    arch=self.arch,
  File "/usr/local/lib/python2.7/dist-packages/angr/engines/vex/engine.py", line 472, in lift
    opt_level=opt_level)
  File "/usr/local/lib/python2.7/dist-packages/pyvex/block.py", line 79, in __init__
    lift(self, arch, mem_addr, data, max_bytes, max_inst, bytes_offset, opt_level, traceflags)
  File "/usr/local/lib/python2.7/dist-packages/pyvex/lift/__init__.py", line 155, in lift
    next_irsb_part = lifter(arch, addr)._lift(u_data, bytes_offset, max_bytes, max_inst, opt_level, traceflags, allow_lookback)
  File "/usr/local/lib/python2.7/dist-packages/pyvex/lift/__init__.py", line 67, in _lift
    self.lift()
  File "/usr/local/lib/python2.7/dist-packages/pyvex/lift/util/lifter_helper.py", line 82, in lift
    instructions = self.decode()
  File "/usr/local/lib/python2.7/dist-packages/pyvex/lift/util/lifter_helper.py", line 77, in decode
    raise e
bitstring.ReadError: Reading off the end of the data. Tried to read 16 bits when only 8 available.
```

The reason for this is following:

When shared library is built for an ARM, if no entry point is specified for it, it will be set to the begining of the "_.text_" section. And address will be always as for the ARM mode, with last bit of address equal to 0.

However, that library can have exported function compiled for thumb mode which is right at the begining of "_.text_" section

For example EP is at **0xbd688** and exported_func is at **0xbd689** according to symbols.

When CFGFast._generate_cfgnode(...) is called for EP address (**0xbd688**) "distance heuristics" inside this function will cut size to 1 byte (**0xbd689**-**0xbd688**=1):

https://github.com/angr/angr/blob/8d60db6de8ebc987b3d19650f55ec263765559ad/angr/analyses/cfg/cfg_fast.py#L3324-L3333

Obviously there is no 1 byte instructions in ARM, so it is marked as undecoded and GymratLifter is called.

GymratLifter gets 1 byte stream, and when my two byte instruction is parsed from stream, it fails here:

https://github.com/angr/pyvex/blob/9e4c3e12d52c61bbaa1f22f731dbb86b9e5e6cef/pyvex/lift/util/instr_helper.py#L157-L165

As a workaround I exclude entry point from analysis if there is symbol at address EP+1.

I thought may be we could add some code to  CFGFast.\_\_init\_\_() to solve this problem?

For example, change this

https://github.com/angr/angr/blob/8d60db6de8ebc987b3d19650f55ec263765559ad/angr/analyses/cfg/cfg_fast.py#L741

To

```
if self.project.loader.main_object.symbols_by_addr[self.project.entry+1] and \
        self.project.arch.name in ('ARMHF', 'ARMEL'):
    self._start_at_entry = False
```
	
Or may be there can be some other workarounds?

**Comment by bennofs** [comment]
The commit https://github.com/angr/pyvex/pull/111/commits/c4e9c9e813e6f80a149a5c43534444c4b13b407c in pr #111 should fix this

**Comment by ArtemShypotilov** [comment]
Oh, thats great! Thanks.
