### ISSUE TITLE
Support for s390

### ISSUE THREAD

**Issue by joxeankoret** [angr/pyvex#13]
Hi!

I plan to use pyvex for a project of mine (http://github.com/joxeankoret/diaphora), basically, to have an intermediate language that can be used to diff programs for different CPUs. Do you have any plan in supporting s390?

This CPU, s390, is actually supported by both VEX and Capstone (SystemZ) so, I guess, that adding it should be as easy as adding a s390 architecture definition python file for the archinfo package.

**Comment by rhelmot** [comment]
Yep! This is an issue for archinfo (which has its own repository), not pyvex, so I'm gonna close this issue. If you'd like to write the archinfo/arch_s90.py file yourself, do that and give us a merge request there. If you want somebody else to do it, just re-open the issue in that repository. Thanks!
