### ISSUE TITLE
IndexError after CFG Fast optimizations

### ISSUE THREAD

**Issue by ArtemShypotilov** [angr/pyvex#143]
Hi Guys!

After CFG Fast optimization I have started seeing exception below:

```
...

 File "/usr/local/lib/python2.7/dist-packages/pyvex/block.py", line 82, in __init__
   lift(self, arch, mem_addr, data, max_bytes, max_inst, bytes_offset, opt_level, traceflags, strict_block_end)
 File "/usr/local/lib/python2.7/dist-packages/pyvex/lifting/__init__.py", line 110, in lift
   final_irsb.extend(more_irsb)
 File "/usr/local/lib/python2.7/dist-packages/pyvex/block.py", line 152, in extend
   replacement = convert_expr(expr)
 File "/usr/local/lib/python2.7/dist-packages/pyvex/block.py", line 130, in convert_expr
   return RdTmp.get_instance(convert_tmp(expr.tmp))
 File "/usr/local/lib/python2.7/dist-packages/pyvex/block.py", line 118, in convert_tmp
   tmp_type = extendwith.tyenv.lookup(tmp)
 File "/usr/local/lib/python2.7/dist-packages/pyvex/block.py", line 480, in lookup
   raise IndexError(tmp)
IndexError: 34
```

it happens during block processing with custom GymRat instruction.

I include my test script [test_cfg_bugs.zip](https://github.com/angr/pyvex/files/2163981/test_cfg_bugs.zip) and test binary [bug_lda.zip](https://github.com/angr/pyvex/files/2163968/bug_lda.zip).

Please help me to solve this issue.

Thanks.

**Comment by ltfish** [comment]
I cannot reproduce this issue -- your script worked well for me, and finished running. Can you debug it a little bit and let me know at which basic block the bug was triggered on your machine?

**Comment by ArtemShypotilov** [comment]
It triggers when processing block at **0x104D1** which contains _NoDecode_ instruction. 
For example, if I put conditional breakpoint (addr == 0x104D1) at:

https://github.com/angr/angr/blob/5211bc8e11a1971b724dc9100cf2b0a873698c82/angr/analyses/cfg/cfg_fast.py#L1680-L1682

I won't step over it without an exception.

I've just rechecked this on different computer, result is the same :( However, it is configured pretty much similar.

Oh, and for this binary exact error is **IndexError: 42**.

**Comment by ArtemShypotilov** [comment]
Strange thing, this error is different for this binary at almost every run. It was like **IndexError: 42**, **IndexError: 43**, **IndexError: 44**.

**Comment by ltfish** [comment]
Maybe it's trying to tell us something...

Joking aside, it seems that something is non-deterministic. My guess is dicts and sets that are used in lifting.

**Comment by ArtemShypotilov** [comment]
I believe debugging influences it somehow.

**Comment by ltfish** [comment]
That's totally possible. I'm debugging something else. Will get back to you soon.

**Comment by ArtemShypotilov** [comment]
I have added statements output to the log at the beginning of 

https://github.com/angr/pyvex/blob/664cacd52339004088a28d669e26cd60ef6a12da/pyvex/block.py#L133-L158

Two logs with different  **IndexError** are attached. 
[log43.txt](https://github.com/angr/pyvex/files/2164414/log43.txt)
[log44.txt](https://github.com/angr/pyvex/files/2164415/log44.txt)

Looks like some strange non-deterministic things happen during replacement of temp variables for `armg_calculate_flag_v`

I just don't understand why its not working for you. Maybe its Pypy or something.

**Comment by ltfish** [comment]
Are you using PyPy? I'm using CPython on Windows when debugging this issue.

**Comment by ArtemShypotilov** [comment]
No, I thought you guys are using PyPy. I'm using CPython on Ubuntu.
