### ISSUE TITLE
Build error: VexControl has no member named ‘strict_block_end’

### ISSUE THREAD

**Issue by qsphan** [angr/pyvex#155]
There are some codes in `pyvex.c` that assign value to the `strict_block_end` field of variable `vc` of type `VexControl`:
```
pyvex.c:130:4: error: ‘VexControl {aka struct <anonymous>}’ has no member named ‘strict_block_end’
  vc.strict_block_end = 0;
        
pyvex.c:318:4: error: ‘VexControl {aka struct <anonymous>}’ has no member named ‘strict_block_end’
  vc.strict_block_end = strict_block_end;    
```
`VexControl` is defined in [libvex.h](https://github.com/angr/vex/blob/master/pub/libvex.h), there is no `strick_block_end` field.

**Comment by rhelmot** [comment]
I'm really not sure what's going on... in the file you linked, ctrl-f'ing for strict_block_end immediately yields the appropriate field.

**Comment by qsphan** [comment]
@rhelmot Interesting, I use Meld to compare my local file and the file on github, and it seems this is the only different. However, `git status` doesn't say this file was modified.

**Comment by qsphan** [comment]
@rhelmot Yes, I check `git log`, and the latest commit is Sep 2017. So the script `setup.sh` downloads the old repository?

**Comment by rhelmot** [comment]
it, uh, really should not. Did you just install this now? If not won't automatically pull everything for you, you have to do git pull yourself.

**Comment by qsphan** [comment]
Yes, I just installed it now. Everything seems OK, except for `ipdb` cannot be installed. Is this a problem?

**Comment by rhelmot** [comment]
what on earth is going on in your environment...? ipdb is a super standard package, and I've never seen if fail to install, unless you've somehow installed the python3-only version or something.

ipdb isn't a hard requirement, you can get away without it. You just can't use the siminspect breakpoints with the "spawn an ipdb shell". furthermore, if you ask for debugging help, we might tell you "write `import ipdb; ipdb.set_trace() on xxx line to set a breakpoint", but it's not a core component of angr.
