### ISSUE TITLE
Python 2.7.15+ Issue: Cannot pass unicode string as data to lifter

### ISSUE THREAD

**Issue by kye4u2** [angr/pyvex#161]
On newer versions of python 2.7 byte == str.

So the check that is performed isinstance(data, str) will always return true and throw the exception

This check should be changed.  A hotfix would be to comment out this check in line 55 of in pyvex/lifting/_init_.py

**Comment by ltfish** [comment]
Are you talking about the latest version on GitHub? If so, we do not support Python 2 any more. Please use the latest version of PyVEX that supports Python 2.

**Comment by ltfish** [comment]
The [`py2k` branch](https://github.com/angr/pyvex/tree/py2kvvv) might be what you need.

**Comment by kye4u2** [comment]
Yep... Oh... Thanks for pointing out that branch.
