### ISSUE TITLE
Do we really need to treat "pop {..,lr,...}; b xxx" as a call jump? (ArchARM)

### ISSUE THREAD

**Issue by danse-macabre** [angr/pyvex#165]
Here I would like to argue with the decision to treat the following code sequence as a call jump:

```
LDMFD   SP!, {R4-R8,LR}
BX R3
```

In 95095fe1893eaaf7d7bda8b0a14846b6facfc70a commit the `arm_post_processor_determine_calls()` was set to change the exit jumpkind of that block from `Ijk_Boring` to `Ijk_Call`. I think this decision is not particularly useful (*or even wrong*), in terms of _what_ the `Ijk_Call` jumpkind does actually mean for the code analysis. 

From my point of view, the purpose of the `Ijk_Call` jumpkind existence is not only to denote that the particular block transfers control to another function (that is, to show that the target address is a function entry point), but also to note that the control flow might somehow return to the address, that follows the call instruction. The latter assertion was expressed in angr in the form of `Ijk_FakeRet`, which is produced per user request for every `Ijk_Call` exit. And in case of *"pop {..,lr,...}; b xxx"*, that assertion is entirely wrong, i.e., there is absolutely zero chance, that the control flow will ever return to the instruction next to the tail-call. Thus, the `Ijk_FakeRet` exit will be quite a misleading hint to the analysis.

Consider the following example: 

- The block at the end of some function A, that ends with a tail-call, gets executed with `DO_RET_EMULATION` option enabled. 
- The execution results in two possible final states: one at the next function entry (we will denote it as function B) and one at the address next to the call instruction (which is probably going to be the start of the current function's constant pool).
- Then, at some point of the analysis, the function return sub-analysis routine is called, and it correctly detects that the function A _does_ return the control (i.e. `function.returning = True`).
- As a result of that, the fake return, that was produced by the first execution gets the "confirmed" status set to True, and now the analysis legitematly thinks that the address next to the call instruction could possible contain the continuation of function A, which is totally wrong.

I'm not quite familliar with how exactly does the CFGAccurate work, but as long as it is relying on some kind of the algorithm described above, there might be a problem, that is yet to be discovered.

Looking forward to hear what you think about it.

**Comment by danse-macabre** [comment]
@subwire Thank you for quick response.

> What we'll probably do is move this stuff into CFGFast or CFGBase, and treat the thing-thats-not-a-call as an explicit "transition".

I think this is a good idea. I've been using the similar solution for quite a while, if we're talking about the same thing. 

Namely, I have a special "scope" property, set on each of the CFG edges. The "scope" may have two possible values: *internal* (denotes the given edge as an *intra*-function transition) and *external* (denotes the given edge as an *inter*-function transition). It is easy to see, that some edges, for example, `Ijk_Call` and `Ijk_Ret` are always "external," while some other edges, such as `Ijk_FakeRet` are always "internal." The `Ijk_Boring` edges can be both "internal" and "external," depending on the context. 

For example, the "pop {..,lr,...}; b xxx"-kind of block will have its default exit edge marked as "external," while the actual jumpkind will be `Ijk_Boring`.

As for the solution of this particular problem, I would propose to set the `Ijk_Call` jumpkind only for those blocks, which explicitly set the LR-register to point to the address, which immediately follows the block.

**Comment by subwire** [comment]
This will (eventually) be fixed in #166
