### ISSUE TITLE
Class representing phi node or phi function

### ISSUE THREAD

**Issue by riyadparvez** [angr/pyvex#17]
I think VEX IR is in SSA form. So there should be phi nodes. Which class in pyvex represents phi node or phi function?

**Comment by zardus** [comment]
There isn't one, really. VEX is SSA for the temporary storage variables within a basic block. Other than that, registers and memory aren't SSA per-se. You can always uniquely identify a memory or register write by a tuple of (basic_block_addr, statement_id), but the merging through phi nodes and so forth, if you need an analysis like that, is not currently done.
