### ISSUE TITLE
problem in archinfo module, it throws an error 

### ISSUE THREAD

**Issue by buptsseGJ** [angr/pyvex#170]
I reinstall pyvex in my Windows OS. Then I try the example on the pyvex website.  
But it throws the error:
```Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import archinfo
  File "C:\Python27\lib\site-packages\archinfo\__init__.py", line 8, in <module>
    from .arch_amd64    import ArchAMD64
  File "C:\Python27\lib\site-packages\archinfo\arch_amd64.py", line 252, in <module>
    register_arch([r'.*amd64|.*x64|.*x86_64|.*metapc'], 64, Endness.LE, ArchAMD64)
  File "C:\Python27\lib\site-packages\archinfo\arch.py", line 655, in register_arch
    all_arches.append(my_arch(endness))
  File "C:\Python27\lib\site-packages\archinfo\arch_amd64.py", line 33, in __init__
    super(ArchAMD64, self).__init__(endness)
  File "C:\Python27\lib\site-packages\archinfo\arch.py", line 195, in __init__
    r.vex_offset = _pyvex.vex_ffi.guest_offsets[(va, name)]
AttributeError: 'module' object has no attribute 'guest_offsets'
```
It hasn't happened before. 
My pyvex version is as follows:
```
C:\Program Files (x86)\Microsoft Visual Studio 14.0>pip install pyvex
Requirement already satisfied: pyvex in c:\python27\lib\site-packages\pyvex-7.7.9.14-py2.7.egg (7.7.9.14)
Requirement already satisfied: pycparser in c:\python27\lib\site-packages (from pyvex) (2.19)
Requirement already satisfied: cffi>=1.0.3 in c:\python27\lib\site-packages (from pyvex) (1.11.5)
Requirement already satisfied: archinfo>=7.7.9.14 in c:\python27\lib\site-packages (from pyvex) (8.18.10.1)
Requirement already satisfied: bitstring in c:\python27\lib\site-packages (from pyvex) (3.1.5)
Requirement already satisfied: future in c:\python27\lib\site-packages (from archinfo>=7.7.9.14->pyvex) (0.16.0)
```
May I ask what causes this problem? Thank you!

**Comment by rhelmot** [comment]
Good question - but I don't know the answer, and I'm not going to be able to help you find the answer, because you're using an old version of pyvex (7). If you can reproduce this on a newer version of pyvex (8, note that this is python 3 only), I will help you.

**Comment by buptsseGJ** [comment]
I note that the archinfo version I used earlier is 7.7.9.14. But now it is 8.18.10.1. So can I replace the new archinfo with the old one in the c:\python27\lib\site-packages directory directly?

**Comment by buptsseGJ** [comment]
I solve that problem by put 7.7.9.14 version archinfo into the c:\python27\lib\site-packages directory though it isn't a good idea. Then it doesn't throw the error. 
I have some analysis task written in Python2.7.  So I need to use version 7 of pyvex according to your description.  So I don't change anything except the archinfo version package.

**Comment by buptsseGJ** [comment]
I solve that problem by putting 7.7.9.14 version archinfo into the c:\python27\lib\site-packages directory though it isn't a good idea. Then it doesn't throw the error.
I have some analysis task written in Python2.7. So I need to use version 7 of pyvex according to your description. So I don't change anything except the archinfo version package.

**Comment by rhelmot** [comment]
If you need to use the old version, then I cannot help you.
