### ISSUE TITLE
The instruction after "clflush" instruction cannot be decoded. 

### ISSUE THREAD

**Issue by benben2301** [angr/pyvex#172]
```
#!/usr/bin/env python
import cle 
import pyvex
import archinfo

if __name__ == '__main__':
    irsb = pyvex.lift(b"\x0f\xae\xf0\x0f\xae\x3f\xc3", 0x400400, archinfo.ArchAMD64())
    irsb.pp()
```
Output:
```
IRSB {
   t0:Ity_I64 t1:Ity_I64 t2:Ity_I64

   00 | ------ IMark(0x400400, 3, 0) ------
   01 | MBusEvent-Imbe_Fence
   02 | ------ IMark(0x400403, 3, 0) ------
   03 | t0 = GET:I64(rdi)
   04 | t1 = And64(t0,0xffffffffffffff00)
   05 | PUT(cmstart) = t1
   06 | PUT(cmlen) = 0x0000000000000100
   NEXT: PUT(rip) = 0x0000000000400406; Ijk_InvalICache
}
```
The instrucitons after "clfush" instruciton cannot be decoded. The bytes in the example code is the following instructions
```
400561:   0f ae f0                mfence 
400564:   0f ae 3f                clflush (%rdi)
400567:   c3                      retq 
```

You can see that there are only two instructions mfence and clflush are translated, but the instruction after "clflush" is not translated ("ret").  In angr, this will finally result in an incompleted CFG, since the RET instruction is missing.

**Comment by rhelmot** [comment]
To reiterate - this isn't a bug in vex but rather a bug in how we handle the block in angr. It is intended that a `clflush` instruction end a block with an Ijk_InvalICache jumpkind - you can see that the `NEXT` instruction does in fact tell us to jump to the `retq` instruction. CFG was just totally failing to think it was a valid jump, just like you!

**Comment by benben2301** [comment]
I think clflush never changes the control flow, could we just ignore (treat it as a normal instruction instead of a jump) it in the CFG?  

BTW, I just curious, the code I posted just the low-level code which is before the CFG generation, by my understanding, the code just translates the machine code to IR, why it still gives the wrong translation?

**Comment by rhelmot** [comment]
The code you posted produces a correct translation. There is a control flow
transition but it is merely directly to the next instruction.

**Comment by benben2301** [comment]
Mfence + ret
```
irsb = pyvex.lift(b"\x0f\xae\x3f\xc3", 0x400400, archinfo.ArchAMD64())
 irsb.pp()
```
 it gives:
```
IRSB {
   t0:Ity_I64 t1:Ity_I64 t2:Ity_I64 t3:Ity_I64 t4:Ity_I64

   00 | ------ IMark(0x400400, 3, 0) ------
   01 | MBusEvent-Imbe_Fence
   02 | PUT(rip) = 0x0000000000400403
   03 | ------ IMark(0x400403, 1, 0) ------
   04 | t0 = GET:I64(rsp)
   05 | t1 = LDle:I64(t0)
   06 | t2 = Add64(t0,0x0000000000000008)
   07 | PUT(rsp) = t2
   08 | t3 = Sub64(t2,0x0000000000000080)
   09 | ====== AbiHint(0xt3, 128, t1) ======
   NEXT: PUT(rip) = t1; Ijk_Ret
}
```
Cflush + ret
```
irsb = pyvex.lift(b"\x0f\xae\x3f\xc3", 0x400400, archinfo.ArchAMD64())
```
 it gives:
```
IRSB {
   t0:Ity_I64 t1:Ity_I64 t2:Ity_I64

   00 | ------ IMark(0x400400, 3, 0) ------
   01 | t0 = GET:I64(rdi)
   02 | t1 = And64(t0,0xffffffffffffff00)
   03 | PUT(cmstart) = t1
   04 | PUT(cmlen) = 0x0000000000000100
   NEXT: PUT(rip) = 0x0000000000400403; Ijk_InvalICache
}
```
In the first example, at least a portion of `ret` insn in the `IRSB{...}` which is changing the `RSP`, but there are nothing related to `ret` in the second example.

**Comment by benben2301** [comment]
Okay, I see. Do we have a quick way to fix this? For example, connecting this basic block to the next `ret` insn? 
But `clflush` should not be treated as a jump, because it never changes the control flow. 
Thanks a lot for your help.

**Comment by rhelmot** [comment]
You would have to change libvex.

This really should not *ever* affect your analysis. There are tons upon
tons of ways that basic blocks will end without there being a jump. For
example, if there are more than 99 instructions in a block the block will
end there. If your analysis requires that every single block end
corresponds to a jump, you will need to create another basic block
representation on top of vex.

**Comment by benben2301** [comment]
It really makes the CFG incompleted, since if there is a basic block contains `clflush` in the critical path, there will be no nodes after this basic block in the CFG.

**Comment by ltfish** [comment]
> ... there will be no nodes after this basic block in the CFG.

If you are using CFGEmulated and are observing this behavior, then that is a bug that has been fixed (see this commit https://github.com/angr/angr/commit/4e4e844efc7a4fc72dc9b093dede7cf3ca6f705d). If you observe that behavior on CFGFast, that should be a bug that we will fix. Please provide a test case then.

But in any case, Ijk_InvalICache will end a basic block and we will not change that behavior. Your analysis should in no way be impacted by this.

**Comment by benben2301** [comment]
Disassembly code of testing program "clflush"
```
120 00000000004004d6 <max>:
121   4004d6:   55                      push   %rbp
122   4004d7:   48 89 e5                mov    %rsp,%rbp
123   4004da:   89 7d fc                mov    %edi,-0x4(%rbp)
124   4004dd:   89 75 f8                mov    %esi,-0x8(%rbp)
125   4004e0:   8b 45 fc                mov    -0x4(%rbp),%eax
126   4004e3:   39 45 f8                cmp    %eax,-0x8(%rbp)
127   4004e6:   0f 4d 45 f8             cmovge -0x8(%rbp),%eax
128   4004ea:   5d                      pop    %rbp
129   4004eb:   c3                      retq
130 
131 00000000004004ec <clflush>:
132   4004ec:   0f ae f0                mfence
133   4004ef:   0f ae 3f                clflush (%rdi)
134   4004f2:   c3                      retq
135 
136 00000000004004f3 <main>:
137   4004f3:   55                      push   %rbp
138   4004f4:   48 89 e5                mov    %rsp,%rbp
139   4004f7:   48 83 ec 10             sub    $0x10,%rsp
140   4004fb:   48 b8 00 00 00 00 07    movabs $0x700000000,%rax
141   400502:   00 00 00 
142   400505:   48 89 45 f8             mov    %rax,-0x8(%rbp)
143   400509:   48 8b 45 f8             mov    -0x8(%rbp),%rax
144   40050d:   48 89 c7                mov    %rax,%rdi
145   400510:   e8 d7 ff ff ff          callq  4004ec <clflush>
146   400515:   be 14 00 00 00          mov    $0x14,%esi
147   40051a:   bf 32 00 00 00          mov    $0x32,%edi
148   40051f:   e8 b2 ff ff ff          callq  4004d6 <max>
149   400524:   b8 00 00 00 00          mov    $0x0,%eax
150   400529:   c9                      leaveq
151   40052a:   c3                      retq
152   40052b:   0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)

```
Testing code:
```
#!/usr/bin/env python
import angr

def check(binary_path):
    proj = angr.Project(binary_path, use_sim_procedures=True, default_analysis_mode='symbolic_approximating', auto_load_libs=False)

    cfg = proj.analyses.CFG()
    #cfg = proj.analyses.CFGEmulated(keep_state=True, enable_advanced_backward_slicing=True, context_sensitivity_level=4)

    for node in cfg.graph.nodes():
        print('---------------------')
        print(node)
        print('Predecessors:')
        for n in node.predecessors:
            print('##' + str(n))
        print('Successors:')
        for n in node.successors:
            print('##' + str(n))
        print('=====================\n')

if __name__ == '__main__':
    test_program = './clflush'
    check(test_program)
```

Output:
```

---------------------
<CFGNode clflush 0x4004ec[6]>
Predecessors:
##<CFGNode main 0x4004f3[34]>
Successors:
=====================

---------------------
<CFGNode max 0x4004d6[22]>
Predecessors:
Successors:
=====================

```
You can see that node `0x4004ec` does not have seccessors, node `0x4004d6` does not have predecessors and successors,  There should be a node starts with address `0x400515`, but it dispears since it should be the seccessor of block `0x4004ec`. 

Both CFGFast and CFGEmulated have problem. Please kindly find the attached program. 
[clflush.zip](https://github.com/angr/pyvex/files/2517862/clflush.zip)

**Comment by rhelmot** [comment]
here is the output on my machine:

```
---------------------
<CFGNode max 0x4004d6[22]>  
Predecessors:        
##<CFGNode main+0x22 0x400515[15]>
Successors:          
##<CFGNode main+0x31 0x400524[7]>                
===================== 
```

We fixed this in the pull request linked to this issue. Please use the most recent version of angr.

**Comment by ltfish** [comment]
```
...

---------------------
<CFGNode clflush 0x4004ec[6]>
Predecessors:
##<CFGNode main 0x4004f3[34]>
Successors:
##<CFGNode clflush+0x6 0x4004f2[1]>
=====================


---------------------
<CFGNode max 0x4004d6[22]>
Predecessors:
##<CFGNode main+0x22 0x400515[15]>
Successors:
##<CFGNode main+0x31 0x400524[7]>
=====================

...
```

Are you using the latest version on master?

**Comment by rhelmot** [comment]
(you will also need the most recent version of pyvex)

**Comment by benben2301** [comment]
I updated angr and pyvex to the latest version, it seems all stuff had been fixed! Thanks a lot.
