### ISSUE TITLE
translate the flags register to vex IR

### ISSUE THREAD

**Issue by qldxsun** [angr/pyvex#174]
I want to get to know which bits of flags register can be affected by a given instruction, using pyvex.
It seems that the value of cc_op is from the translation of the flags register.
But how can I know exactly which bits of the flags register are affected from a given vex IR set?
For example, in x86, the add instruction can be translated into vex:
          ... ...
          PUT(cc_op)  = 0x00000003
           PUT(cc_dep1) = t2                           the first oprand
           PUT(cc_dep2) = t1                           the second oprand
           ... ...
So, Can I get to know which bits of the flags register can be affected by vex IR set of an instruction?

**Comment by rhelmot** [comment]
Very complicated. vex explicitly does _not_ compute this information because it is very expensive. We have implementations of the translations between the cc registers and the eflags in angr (angr/engines/vex/ccall.py mostly), and these are re-implementations of vex/priv/guest_{arch}_helpers.c.
