### ISSUE TITLE
Binop Uses '_op' slot. Other operations us 'op'.

### ISSUE THREAD

**Issue by dgrahn** [angr/pyvex#179]
Binop is the only operation which uses the '_op' slot for the operation type. All the other's use 'op'. This should be harmonized.

**Comment by rhelmot** [comment]
```python
    @property
    def op(self):
        if self._op is None:
            self._op = get_enum_from_int(self.op_int)
        return self._op
```

It is an optimization to only call get_enum_from_int (which presumably takes a large portion of time for some workloads) when actually necessary. `.op` still exists, it's just a property and not a slot.

**Comment by dgrahn** [comment]
Sorry that it's taken so long for me to respond here. Should this optimization then be applied to the other operations?

**Comment by rhelmot** [comment]
We did not notice that other ops were suffering as much from the op enum lookup as was binop, so we didn't deem it necessary, but yes, it would technically be an improvement.
