### ISSUE TITLE
Expression Operation Object Hierarchy

### ISSUE THREAD

**Issue by dgrahn** [angr/pyvex#181]
VEX has the following expressions, each with the specified properties.

    Unop: op, args
    Binop: op, args
    Triop: op, args
    Quop: op, args

Despite the similarities, these are separate classes. This results in the following:

1. Optimization applied to `Binop` is not applied to other operations.
2. Code duplication.

I recommend creating a parent class which will abstract out the similarities, making maintenance easier. If I get approval, I'll take care of this myself.

**Comment by rhelmot** [comment]
I don't think this is useful. Yes, it will simplify the code, but I believe it will slow it down as well. pyvex is very hot code, and in most cases speed is valued over readability and hygene.
