### ISSUE TITLE
is the system "angr"  can run in windows?

### ISSUE THREAD

**Issue by geemion** [angr/pyvex#20]
#when  i  install in windows 7 x86
i use pip install all the packages,when i 
import angr

there will be a errno, C:\python27\lib\pyvex_static.so  is a errno image,when i use setup.py install pyvex ,there always a errno 

so i don't known what i can do to solve the problem

#when i install in ubuntu 14.04 x64
xx@xx-virtual-machine:~/project$ python helloword.py
Warning: FastBinaryTree not available, using Python version BinaryTree.
Warning: FastAVLTree not available, using Python version AVLTree.
Warning: FastRBTree not available, using Python version RBTree.
Traceback (most recent call last):
  File "helloword.py", line 2, in <module>
    proj= angr.Project("hellowordx64")
  File "/usr/local/lib/python2.7/dist-packages/angr/project.py", line 152, in __init__
    self._simos.configure_project()
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 125, in configure_project
    super(SimLinux, self).configure_project()
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 42, in configure_project
    self.proj.loader.perform_irelative_relocs(irelative_resolver)
  File "/usr/local/lib/python2.7/dist-packages/cle-4.5.11.23-py2.7.egg/cle/loader.py", line 704, in perform_irelative_relocs
    val = resolver_func(resolver)
  File "/usr/local/lib/python2.7/dist-packages/angr/simos.py", line 31, in irelative_resolver
    val = resolver()
  File "/usr/local/lib/python2.7/dist-packages/angr/surveyors/caller.py", line 41, in call_get_return_val
    return self.get_call_results(*args)[0]
  File "/usr/local/lib/python2.7/dist-packages/angr/surveyors/caller.py", line 74, in get_call_results
    caller_end_unpruned = caller.step(until=lambda pg: len(pg.active) == 0, step_func=step_func if self._concrete_only else None).unstash(from_stash='deadended')
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 536, in step
    pg = pg._one_step(stash=stash, selector_func=selector_func, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 342, in _one_step
    r = self._one_path_step(a, successor_func=successor_func, check_func=check_func, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path_group.py", line 287, in _one_path_step
    successors = a.step(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/angr/path.py", line 221, in step
    self._make_sim_run()
  File "/usr/local/lib/python2.7/dist-packages/angr/path.py", line 246, in _make_sim_run
    self._run = self._project.factory.sim_run(self.state, **self._run_args)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 117, in sim_run
    r = self.sim_block(state, addr=addr, **block_opts)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 59, in sim_block
    **block_opts)
  File "/usr/local/lib/python2.7/dist-packages/angr/lifter.py", line 116, in lift
    traceflags=traceflags)
  File "/usr/local/lib/python2.7/dist-packages/pyvex-4.5.11.23-py2.7.egg/pyvex/__init__.py", line 136, in __init__
    c_irsb = pvc.vex_block_bytes(vex_arch, arch.vex_archinfo, c_bytes + bytes_offset, mem_addr, num_bytes, 1)
KeyError: 'x86_cr0'

**Comment by zardus** [comment]
With windows, you're mostly on your own. There have been reports of successes, but I have absolutely no idea how to proceed there.

For the cr0 error, @ronnychevalier might have some ideas? If not, I can look into this sometime next week...

**Comment by rhelmot** [comment]
For windows, you have to do the compiling and installation on your own, no using pip.

On linux, your error looks like a version mismatch error. Make sure your versions of archinfo and pyvex are up to date.

**Comment by geemion** [comment]
ana (0.01)
angr (4.5.11.23)
angr-z3 (4.4.2)
apt-xapian-index (0.45)
archinfo (4.5.11.23)
argparse (1.2.1)
BeautifulSoup (3.2.1)
beautifulsoup4 (4.4.1)
bintrees (2.0.2)
binwalk (2.0.0)
capstone (3.0.4)
cffi (1.3.1)
chardet (2.0.1)
claripy (4.5.11.23)
cle (4.5.11.23)
colorama (0.2.5)
command-not-found (0.3)
cooldict (1.01)
debtagshw (0.1)
decorator (3.4.0)
defer (1.0.6)
dirspec (13.10)
dissy (9)
dpkt-fix (1.7)
fpconst (0.7.2)
futures (3.0.3)
hachoir-core (1.3.3)
hachoir-parser (1.3.4)
html2text (2015.11.4)
html5lib (0.999)
httplib2 (0.8)
idalink (0.11)
impacket (0.9.10)
lxml (3.3.3)
Magic-file-extensions (0.2)
Mako (0.9.1)
MarkupSafe (0.18)
MAT (0.4-rc)
matplotlib (1.3.1)
mulpyplexer (0.07)
mutagen (1.22)
networkx (1.10)
nose (1.3.1)
numpy (1.8.2)
oauthlib (0.6.1)
oneconf (0.3.7.14.04.1)
openpyxl (1.7.0)
PAM (0.4.2)
paramiko (1.10.1)
pcapy (0.10.8)
pdfrw (0.1)
pefile (1.2.9.1)
pexpect (3.1)
Pillow (2.3.0)
pip (1.5.4)
piston-mini-client (0.7.5)
plumbum (1.6.0)
prettytable (0.7.2)
progressbar (2.3)
psutil (1.2.1)
pybloomfiltermmap (0.3.11)
pycparser (2.14)
pycrypto (2.6.1)
pycups (1.9.66)
pycurl (7.19.3)
pyelftools (0.23)
pygobject (3.12.0)
PyOpenGL (3.0.2)
pyOpenSSL (0.13)
pyparsing (2.0.1)
pyPdf (1.13)
pyqtgraph (0.0.0)
pyrit (0.4.0)
pyserial (2.6)
pysmbc (1.0.14.1)
pysqlite (2.6.3)
python-apt (0.9.3.5ubuntu1)
python-dateutil (1.5)
python-debian (0.1.21-nmu2ubuntu2)
python-socksipy (1.0)
pytz (2012c)
pyvex (4.5.11.23)
pyxdg (0.25)
PyYAML (3.10)
reportlab (3.0)
requests (2.2.1)
rpyc (3.3.0)
scapy (2.2.0)
scipy (0.13.3)
sessioninstaller (0.0.0)
setuptools (3.3)
simplejson (3.3.1)
simuvex (4.5.11.23)
six (1.5.2)
SOAPpy (0.12.0)
software-center-aptd-plugins (0.0.0)
SQLAlchemy (0.8.4)
ssh-import-id (3.21)
stevedore (0.14.1)
termcolor (1.1.0)
Twisted-Core (13.2.0)
Twisted-Web (13.2.0)
urllib3 (1.7.1)
vinetto (0.06alpha)
virtualenv (1.11.4)
virtualenv-clone (0.2.4)
virtualenvwrapper (4.1.1)
volatility (2.3.1)
wapiti (2.3.0)
wheel (0.24.0)
wsgiref (0.1.2)
wxPython (2.8.12.1)
wxPython-common (2.8.12.1)
yara-python (2.0)
zenmap (6.47)
zim (0.60)
zope.interface (4.0.5)

**Comment by geemion** [comment]
i fix  it by installing again,before the ubuntu is backbox(a modified ubuntu),now i use the ubuntu is the Not modified ubuntu.but i don't known why

**Comment by zardus** [comment]
Cool! So it works now?

**Comment by geemion** [comment]
yes,but i don't konw what angr can do besides the example and the detail usages.I am
 learning.thank you

**Comment by zardus** [comment]
Good luck!
