### ISSUE TITLE
Possibly incorrect lifting of mov instructions about segment registers on ArchAMD64

### ISSUE THREAD

**Issue by acdxvfsvd** [angr/pyvex#227]
I am using pyvex to analyze Linux kernel and needed to lift the following basic block into VEX.IR:
```
0xffffffff81001880 mov fs, eax
0xffffffff81001882 test esi, esi
0xffffffff81001884 je 0xffffffff81001582
```
code:
```python
buffer = b'\x8e\xe0\x85\xf6\x0f\x84\xf8\xfc\xff\xff'
irsb = pyvex.lift(buffer, 0xffffffff81001880, archinfo.ArchAMD64(), opt_level = 0)
```

result:
```python
>>> irsb.pp()
IRSB {
   

   NEXT: PUT(rip) = 0xffffffff81001880; Ijk_NoDecode
}

```

I found `guest_amd64_assume_fs_is_const ` variable in `pyvex_c/pyvex.c`, but after changing it to False and recompiling the library, it returned the same result.

BTW, when I skipped the first instruction and lifting the other ones, it works normally.

code:
```python 
buffer = b'\x85\xf6\x0f\x84\xf8\xfc\xff\xff'
irsb = pyvex.lift(buffer, 0xffffffff81001882, archinfo.ArchAMD64(), opt_level = 0)

```

result:
```python
>>> irsb.pp()
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I64 t5:Ity_I32 t6:Ity_I64 t7:Ity_I64 t8:Ity_I1 t9:Ity_I64 t10:Ity_I64 t11:Ity_I64 t12:Ity_I64 t13:Ity_I64 t14:Ity_I64

   00 | ------ IMark(0xffffffff81001882, 2, 0) ------
   01 | t4 = GET:I64(rsi)
   02 | t3 = 64to32(t4)
   03 | t2 = t3
   04 | t6 = GET:I64(rsi)
   05 | t5 = 64to32(t6)
   06 | t1 = t5
   07 | t0 = And32(t2,t1)
   08 | PUT(cc_op) = 0x0000000000000013
   09 | t7 = 32Uto64(t0)
   10 | PUT(cc_dep1) = t7
   11 | PUT(cc_dep2) = 0x0000000000000000
   12 | PUT(rip) = 0xffffffff81001884
   13 | ------ IMark(0xffffffff81001884, 6, 0) ------
   14 | t9 = GET:I64(cc_op)
   15 | t10 = GET:I64(cc_dep1)
   16 | t11 = GET:I64(cc_dep2)
   17 | t12 = GET:I64(cc_ndep)
   18 | t13 = amd64g_calculate_condition(0x0000000000000004,t9,t10,t11,t12):Ity_I64
   19 | t8 = 64to1(t13)
   20 | if (t8) { PUT(rip) = 0xffffffff81001582; Ijk_Boring }
   21 | PUT(rip) = 0xffffffff8100188a
   22 | t14 = GET:I64(rip)
   NEXT: PUT(rip) = t14; Ijk_Boring
}

```

**Comment by rhelmot** [comment]
so... vex is just completely and utterly not set up to be able to analyze amd64 programs using segment registers as anything other than constant-offset selectors. It's just so very hardcoded for the linux userland case.

However, I'm not really sure how it's even legal to use segment registers like this in the amd64 ISA. I thought they basically got rid of the segment registers for long mode. Are you sure this isn't 32-bit code? From doing a little bit of reading I suppose you still might be able to use the segment registers just to load and store 16-bit values to them, and maybe the GDT limit (but not the base?) will still apply, but it seems weird. Maybe the right thing to do is to emulate these instructions as nops using a spotter? Would that work for your use case?
