### ISSUE TITLE
Default values for cc registers?

### ISSUE THREAD

**Issue by hwu71** [angr/pyvex#237]
I'm writing something to translate the behaviors of vex statements into z3 expressions. So I will need to re-write the `angr.engines.vex.claripy.ccall` functions like `armg_calculate_flag_v`, etc. 

However, I found that in some of the blocks, there are no `PUT` statements before the `GET` statements from cc_op, cc_dep1, etc (see statements 20-26). Is this valid? If yes, what's the default value for those registers that I would need to pass to `armg_calculate_flag_v` function?
![image](https://user-images.githubusercontent.com/43049320/131763549-3b8fb11d-b19e-4aa9-949a-b8a041093f7d.png)

**Comment by ltfish** [comment]
> Is this valid?

Yes. They carried over are from previous blocks.

**Comment by hwu71** [comment]
Thanks for your quick reply.

Since it's already the first basic block for function at address 0x123cd, when you say previous blocks, are you referring to the caller's blocks?

**Comment by ltfish** [comment]
I think it's fine to use 0s for all of them in this case.

**Comment by rhelmot** [comment]
well... the answer is that it depends on what you want the CPU state at the beginning of execution to be. You probably want cc_op to be OP_COPY, and then cc_dep1 is just whatever the flags register should be. You can make this concrete or symbolic.

**Comment by ltfish** [comment]
@rhelmot is right. Note that the execution of this basic block has nothing to do with `cc_xx` registers. The initial state of your CPU will impact the execution of _future_ blocks, but not this one.
