### ISSUE TITLE
Is ppc / ppc64 / ppc64le supported?

### ISSUE THREAD

**Issue by pkubaj** [angr/pyvex#239]
I can see ppc* code at https://github.com/angr/pyvex/blob/master/pyvex_c/pyvex.c#L242, but currently build fails due to missing elif at https://github.com/angr/pyvex/blob/master/pyvex_c/pyvex.c#L163.

**Comment by ltfish** [comment]
I believe `arch_host` specifies the host machine (i.e., where vex is running on). libVEX (and PyVEX) supports PPC/PPC64 as a guest architecture.

**Comment by rhelmot** [comment]
To elaborate - we _should_ ideally support ppc and friends as both hosts and guests. We don't have any ppc machines lying around to be able to test this, so we would need to ask you to submit patches that enable compilation on ppc hosts.
