### ISSUE TITLE
#include <ffi.h> No Such File or Directory Even after installing libffi-dev

### ISSUE THREAD

**Issue by Adersh97** [angr/pyvex#241]
When trying to setup pyvex, the following error occurs. 

> ERROR: Command errored out with exit status 1:
>    command: /usr/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/root/repos/pyvex/setup.py'"'"'; __file__='"'"'/root/repos/pyvex/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-n34qozx0
>        cwd: /root/repos/pyvex/
>   Complete output (143 lines):
>   c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
>    #include <ffi.h>
>             ^~~~~~~
>   compilation terminated

.

I tried the following commands :

```
sudo apt-get install libffi7 libffi-dev
pip install cffi
CFLAGS=-I/usr/include/libffi/include pip install pyOpenSSL
```

I can see that ffi.h is present at /usr/include/x86_64-linux-gnu/ffi.h

There error still persists. I Use Ubuntu 20.04, Python 3.8 version.

**Comment by ltfish** [comment]
`sudo apt install libffi-dev`

**Comment by ltfish** [comment]
Oh then it's possible that `libffi-dev` is missing in one of the Docker containers, but it is installed in your host system.

Which container was having this issue?

**Comment by Adersh97** [comment]
it first happened when it was trying to build logger service.  but then when I tried to comment out logger service in yml and build the rest , it started to pop on the other repos too. i tried building with docker-compose build --no-cache , it didn't help either
