### ISSUE TITLE
How to model program termination

### ISSUE THREAD

**Issue by ulugbekna** [angr/pyvex#248]
Hi 👋

I’m writing my own lifter for eBPF bytecode and have questions on how to lift an exit instruction (the one that signals exiting from the program):

1. Should I invoke `self.jump(None, ???, JumpKind.Exit)`? If yes, I don’t understand what to put instead of `???`
2. The program should exit with a value of one of its register `(r0)`, how can one model that?

**Comment by ltfish** [comment]
Have you seen https://github.com/angr/angr-platforms/tree/master/angr_platforms/bpf?

**Comment by ulugbekna** [comment]
Hi, yes, but it's for bpf -- not _extended_ BPF, which has different ISA (e.g., more registers and different instructions organization)

If you meant to recommend using it as a reference, I see that the `RET` instruction implementation for bpf has the code below, but I'm not sure: 
1) I should do the same thing on program termination -- it seems to assume that RET just returns from function while I want program termination
2) There is FIXME, so not sure it's a good reference to look at

```
self.jump(0, self.constant(MAX_INSTR_ID * 8, Type.int_32),  # TODO: FIXME
                  JumpKind.Ret
                  )
```

**Comment by rhelmot** [comment]
The best way to do this is to jump to a specific terminator address and then make the simos for your architecture hook that address with a simprocedure that does an exit.

**Comment by ulugbekna** [comment]
Hi @rhelmot ,

Thanks for your reply. 

Could you please elaborate on what a "terminator address" is? 

I tried implementing what you said by overriding SimOS and setting a hook in the constructor as such 

```python3
class ExitSimProcedure(SimProcedure):
    def run(self, exit_code):
        self.exit(exit_code)


class SimOsEbpf(SimOS):
    SYSCALL_TABLE = {}  # TODO: update

    def __init__(self, *args, **kwargs):
        super(SimOsEbpf, self).__init__(*args, name="eBPF", **kwargs)
        self.project.hook(0, ExitSimProcedure())


register_simos('UNIX - System V', SimOsEbpf)
```

Does this make sense?

**Comment by rhelmot** [comment]
Yes, you understand perfectly. A terminator address is an arbitrarily chosen address (we usually allocate one in proj.loader.extern_object) which is hooked by a simprocedure that produces no successors, like the one you've set up.

I actually just read through the code again and it turns out you don't even have to set a terminator address - you can just jump wherever you want with a jumpkind of `Ijk_Exit` and the engine will see that as a cue to stop producing successors.

**Comment by ulugbekna** [comment]
Big thanks! I managed to do this. I have some questions: 

1. So I use arbitrary (currently, zero) as the address of termination simprocedure. However, I would imagine that picking an arbitrary number may result in wrong execution, e.g., a user's program's unintended jump results in a normal program termination, which I would expect some warnings for. Do you have any ideas of how this arbitrary address binding could be fixed? 
2. What's the common way to extract the executed program's exit code?
