### ISSUE TITLE
Can't install on mips64 system

### ISSUE THREAD

**Issue by an-oo-na** [angr/pyvex#341]
I initially tried to install angr via pip, but it failed during the pyvex install. I checked the source code and found that there is no check for mips in pyvex.c. So I downloaded the source code, added the following code in pyvex.c, and used `pip install .`

```
#elif __mips64
        vta.arch_host = VexArchMIPS64;
```
Thankfully, the installation was successful. But when I use import pyvex on the command line, an error occurs:
```
>>> import pyvex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/admin/pyvex/pyvex/__init__.py", line 7, in <module>
    from . import const, expr, stmt
  File "/home/admin/pyvex/pyvex/expr.py", line 929, in <module>
    enum_to_expr_mapping[get_int_from_enum(cls.tag)] = cls
  File "/home/admin/pyvex/pyvex/enums.py", line 109, in get_int_from_enum
    return enums_to_ints[e]
KeyError: 'Iex_Binder'
```
I have no idea now, what should I do next？

**Comment by an-oo-na** [comment]
Thanks for your answer. For some reason I had to install angr on a mips64 system :(. I'm fixing issues I encountered.

**Comment by twizmwazin** [comment]
While we don't have the infrastructure to test it, any patches to improve compatibility are welcome!
