### ISSUE TITLE
Submodule can't be cloned: not our ref

### ISSUE THREAD

**Issue by waarmond** [angr/pyvex#396]
### Description

```
git upload-pack: not our ref 8f48c00eadbb31d379b829c01792a9c4a21636d4
upload-pack: not our ref 8f48c00eadbb31d379b829c01792a9c4a21636d4
```

### Steps to reproduce the bug
${srcdir} stands for the Arch (PKGBUILD) srcdir
```
  git submodule init
  git config submodule."vex".url "${srcdir}/vex"
  git -c protocol.file.allow=always submodule update --recursive
```
`python -m build --wheel --no-isolation`

### Environment

Python 3.10, Linux

**Comment by rhelmot** [comment]
It looks like this commit used to exist but got force pushed over and garbage collected. @twizmwazin do you know what happened? I think a3f558b7 should be equivalent, as I still have 8f48c00 on my local machine and git diff says they're the same.

**Comment by waarmond** [comment]
Clicking the https://github.com/angr/vex/tree/8f48c00eadbb31d379b829c01792a9c4a21636d4 links lets Github display _This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository._
