### ISSUE TITLE
Can't install pyvex on OSX

### ISSUE THREAD

**Issue by damnya** [angr/pyvex#40]
ld: unknown option: -soname
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make: **\* [libpyvex.dylib] Error 1
  error: Unable to build pyvex-static.

---

  Failed building wheel for pyvex

It looks like "-soname" should replace with "-install_name" on OSX?

**Comment by rhelmot** [comment]
This is my fault!! I rehauled the setup process for this repo and I
neglected to test it anywhere but on Linux :(

I will read up on the way this works and push something for you to try very
soon, maybe 3 hours from now. Thank you for reporting!

**Comment by damnya** [comment]
thank you for the reply，after replace soname with install_name，I test pip install from local package，and it worked now.Looking forward to the update：）

**Comment by rhelmot** [comment]
New version is released! Also, I fixed some issues, and the download should now be 0.4% the size it previously was! Let me know if it works, since I don't have an os x to test on :(

**Comment by damnya** [comment]
raymonddeMBP:~ sun$ pip install pyvex
Collecting pyvex
  Downloading pyvex-5.6.8.25.tar.gz (42kB)
    100% |████████████████████████████████| 51kB 34kB/s 
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/site-packages (from pyvex)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.0.3 in /usr/local/lib/python2.7/site-packages (from pyvex)
Requirement already satisfied (use --upgrade to upgrade): archinfo in /usr/local/lib/python2.7/site-packages (from pyvex)
Requirement already satisfied (use --upgrade to upgrade): pyelftools in /usr/local/lib/python2.7/site-packages (from archinfo->pyvex)
Requirement already satisfied (use --upgrade to upgrade): capstone in /usr/local/lib/python2.7/site-packages (from archinfo->pyvex)
Building wheels for collected packages: pyvex
  Running setup.py bdist_wheel for pyvex ... done
  Stored in directory: /Users/sun/Library/Caches/pip/wheels/f0/27/6d/727fbe28eacea3cd83afb2dbc36da0c996388ba7918dfb6f60
Successfully built pyvex

Seems everything ok now,thanks!
