### ISSUE TITLE
Fails to install for Mac OS X [stdio.h missing]

### ISSUE THREAD

**Issue by cLupus** [angr/pyvex#42]
I'm trying to install angr on my my Mac, but when pyrex is to be installed, it fails. More specifically, paved-static fails, and gives the error message:

Building pyvex-static
  gcc -O2 -shared -fPIC -I.././vex-master/pub --std=c99 -o libpyvex.dylib pyvex.c logging.c .././vex-master/libvex.a -Wl,-install_name,libpyvex.dylib
  gcc: warning: couldn’t understand kern.osversion ‘16.0.0
  pyvex.c:20:19: fatal error: stdio.h: No such file or directory
   #include <stdio.h>
                     ^
  compilation terminated.
  logging.c:3:19: fatal error: stdio.h: No such file or directory
   #include <stdio.h>
                     ^
  compilation terminated.
  make: **\* [libpyvex.dylib] Error 1
  error: Unable to build pyvex-static.

---

  Failed building wheel for pyvex
  Running setup.py clean for pyvex
Failed to build pyvex
Installing collected packages: pyvex
  Running setup.py install for pyvex ... error
    Complete output from command /Users/*_**/anaconda/envs/sechac/bin/python -u -c "import setuptools, tokenize;**file**='/private/var/folders/ch/wbqzf6z51gx086gw118yv0qr0000gn/T/pip-build-bNmIkU/pyvex/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/ch/wbqzf6z51gx086gw118yv0qr0000gn/T/pip-hWEblB-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Building libVEX
    EXTRA_CFLAGS="-fPIC -w " make -f Makefile-gcc
    make[1]: Nothing to be done for `all'.
    Building pyvex-static
    gcc -O2 -shared -fPIC -I.././vex-master/pub --std=c99 -o libpyvex.dylib pyvex.c logging.c .././vex-master/libvex.a -Wl,-install_name,libpyvex.dylib
    gcc: warning: couldn’t understand kern.osversion ‘16.0.0
    pyvex.c:20:19: fatal error: stdio.h: No such file or directory
     #include <stdio.h>
                       ^
    compilation terminated.
    logging.c:3:19: fatal error: stdio.h: No such file or directory
     #include <stdio.h>
                       ^
    compilation terminated.
    make: *_\* [libpyvex.dylib] Error 1
    error: Unable to build pyvex-static.

```
----------------------------------------
```

Command "/Users/user/anaconda/envs/sechac/bin/python -u -c "import setuptools, tokenize;**file**='/private/var/folders/ch/wbqzf6z51gx086gw118yv0qr0000gn/T/pip-build-bNmIkU/pyvex/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/ch/wbqzf6z51gx086gw118yv0qr0000gn/T/pip-hWEblB-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ch/wbqzf6z51gx086gw118yv0qr0000gn/T/pip-build-bNmIkU/pyvex/

**Comment by zardus** [comment]
`stdio.h` is part of the standard C library. Are you sure that your build environment is set up properly?

**Comment by cLupus** [comment]
It should be, a virtual environment with (ana)conda wich pretty much just contains python 2.7. gcc version 4.7, and 6 (I think) are installed, along with misc. libraries (including the standard library). Could there be an error somewehere else in the code, but such that the compiler only reacts to headers, it thinks are missing?

**Comment by zardus** [comment]
I am not sure... The core angr guys don't have a mac dev env handy anywhere.

@cao has had luck getting pyvex working on OSX. Maybe he's seen this before?

**Comment by rhelmot** [comment]
Ultimately, this is the line that's failing:

`gcc -O2 -shared -fPIC -I.././vex-master/pub --std=c99 -o libpyvex.dylib pyvex.c logging.c .././vex-master/libvex.a -Wl,-install_name,libpyvex.dylib`

Try to see if you can sit in the simuvex_c directory and execute this. If it works, then it's a problem on our end. If it fails, it's a problem on your end, and you've got a good place to start debugging it.

**Comment by cLupus** [comment]
There has been a strange development; When I try to compile it with CLion, there are a lot of headers that are "missing", CLion looks for them in the wrong directory. I fixed this, but then there is the header "elf.h", which CLion (when compiling) is able to find. This happens in the files "vex-master/switchback/linker.c" (line 15) and in "vex-master/unused/linker.c" (line 8).

**Comment by rhelmot** [comment]
Hi, I don't know if you still care or not, but I still think this is an issue with CLion - the files you mention aren't supposed to be used during a normal build of libVEX.
