### ISSUE TITLE
Build of libVEX fails on Mac OS X with default Clang

### ISSUE THREAD

**Issue by mattrepl** [angr/pyvex#56]
The fix for #53 added the -malign-double compiler flag. Unfortunately this flag is not supported in the version of Clang (Apple LLVM version 8.0.0 (clang-800.0.42.1)) that ships with Mac OS X Sierra (10.12.3).

Current workarounds are either installing a newer version of Clang that supports the flag or to create a `vex` directory (copy `vex-master` in `pyvex/`) and removing the `-malign-double` flag from `Makefile-gcc`.

**Comment by rhelmot** [comment]
FYI: this has been fixed on my current development branch, but that branch is also a gigantic rebase of vex on upstream and a cleanup of our git history in preparation of submitting our changes to valgrind, so it's not getting pushed for a few days...

**Comment by vancaho** [comment]
@mattrepl Have you installed pyvex on Mac OSx Sierra (10.12.3) successfully? I have the same problem with you, but after removing the -malign-double flag, another error is reported:  File "/pyvex/make_ffi.py", line 92, in doit
    raise Exception("Couldn't process pyvex headers - set CPP env var")
Could you please give me some good suggestion? Thanks

**Comment by rhelmot** [comment]
That error message you are seeing was actually added more recently than this issue was opened: https://github.com/angr/pyvex/pull/55/files

I would recommend enabling logging so you can see the error messages being logged.

**Comment by shelvenzhou** [comment]
@vancaho same problem with you
just revert the change introduced by
https://github.com/angr/pyvex/pull/55/files
and everything will be okay

**Comment by rhelmot** [comment]
@f0rki your change is causing issues on os x, do you have any insight to why that might be?

**Comment by f0rki** [comment]
Strange. Maybe we should also add `-E` in case `CPP` points to another compiler binary (e.g. `clang` or `gcc`) to run the preprocessor?

@shelvenzhou can you import pyvex after reverting and installing? What is the `cpp` binary on your system? Is it Can you execute `python make_ffi.py ../vex/pub` (or wherever your vex master is) script manually? then you should get debug output and see what has failed.

**Comment by shelvenzhou** [comment]
@f0rki yes everything works properly.

Here's the output of my `cpp -v`:

> Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 274.1 -v -dwarf-column-info -debugger-tuning=lldb -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0 -I /usr/include -fdebug-compilation-dir /Users/Shelven/Downloads/pyvex -ferror-limit 19 -fmessage-length 181 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -traditional-cpp -o - -x c -
clang -cc1 version 8.0.0 (clang-800.0.42.1) default target x86_64-apple-darwin16.4.0
ignoring duplicate directory "/usr/include"
  as it is a non-system directory that duplicates a system directory
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.

And the result of `python make_ffi.py ../vex/pub`

> WARNING:cffier:failed commands:
cl -I../vex/pub pyvex_c/pyvex.h -E -- does not exist
cpp -I../vex/pub pyvex_c/pyvex.h -- In file included from pyvex_c/pyvex.h:6:
In file included from ../vex/pub/libvex.h:41:
../vex/pub/libvex_ir.h:490:59: warning: missing terminating ' character [-Winvalid-pp-token]
                    //                    concat with 64 0's (low))
                                                          ^
../vex/pub/libvex_ir.h:493:40: warning: missing terminating ' character [-Winvalid-pp-token]
                    // concat with 32 0's (low))
                                       ^
In file included from pyvex_c/pyvex.h:6:
In file included from ../vex/pub/libvex.h:43:
In file included from ../vex/pub/e4c_lite.h:12:
In file included from /usr/include/setjmp.h:27:
In file included from /usr/include/Availability.h:184:
/usr/include/AvailabilityInternal.h:20265:10: error: #else without #if
        #else
         ^
/usr/include/AvailabilityInternal.h:20832:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_11_4
         ^
/usr/include/AvailabilityInternal.h:20765:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_11_3
         ^
/usr/include/AvailabilityInternal.h:20702:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_11_2
         ^
/usr/include/AvailabilityInternal.h:20643:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_11
         ^
/usr/include/AvailabilityInternal.h:20588:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_10_3
         ^
/usr/include/AvailabilityInternal.h:20537:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_10_2
         ^
/usr/include/AvailabilityInternal.h:20490:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_10
         ^
/usr/include/AvailabilityInternal.h:20447:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_9
         ^
/usr/include/AvailabilityInternal.h:20408:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_8
         ^
/usr/include/AvailabilityInternal.h:20373:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_7
         ^
/usr/include/AvailabilityInternal.h:20342:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_6
         ^
/usr/include/AvailabilityInternal.h:20315:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_5
         ^
/usr/include/AvailabilityInternal.h:20292:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_4
         ^
/usr/include/AvailabilityInternal.h:20273:10: error: unterminated conditional directive
        #if __MAC_OS_X_VERSION_MIN_REQUIRED >= __MAC_10_3
         ^
In file included from pyvex_c/pyvex.h:6:
In file included from ../vex/pub/libvex.h:43:
In file included from ../vex/pub/e4c_lite.h:12:
In file included from /usr/include/setjmp.h:27:
/usr/include/Availability.h:233:2: error: #else without #if
#else
 ^
/usr/include/Availability.h:236:2: error: #endif without #if
#endif
 ^
/usr/include/Availability.h:272:2: error: #endif without #if
#endif
 ^
/usr/include/Availability.h:299:2: error: #endif without #if
#endif
 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
Traceback (most recent call last):
  File "make_ffi.py", line 114, in <module>
    doit(sys.argv[1])
  File "make_ffi.py", line 83, in doit
    raise Exception("Couldn't process pyvex headers - set CPP env var")
Exception: Couldn't process pyvex headers - set CPP env var

**Comment by shelvenzhou** [comment]
To make the problem clear, this version works
https://github.com/angr/pyvex/commit/c81cc1c4bfba4d598b0fb323fc71f5651bd64f54#diff-880d547726be1f58bf8980866c662020

**Comment by f0rki** [comment]
This is pretty strange. I don't get how it works without the error checking. Is pyvex working normally for you? I don't know how clang cpp can throw fatal error messages and still produce usable output? 

My pull request basically just added a check for the return code and stderr. Maybe the latter is the problem... I changed it a little, can you please try [this branch](https://github.com/f0rki/pyvex/tree/fix-cpp-call-mac)?

**Comment by mattrepl** [comment]
@f0rki I tried your updated `make_ffi.py` and get the same result as @shelvenzhou.

**Comment by f0rki** [comment]
Can you post the output of the `make_ffi.py` script? And also of running `cpp -I../vex/pub pyvex_c/pyvex.h >out.log 2>err.log` and the exit code?

On February 9, 2017 8:00:42 PM GMT+01:00, Matt Revelle <notifications@github.com> wrote:
>@f0rki I tried your updated `make_ffi.py` and get the same result as
>@shelvenzhou.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/angr/pyvex/issues/56#issuecomment-278738815

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mattrepl** [comment]
The exit code for running `cpp` is `1`. I didn't include the output of running `make_ffi.py` as it's the same as the attached error log and I already reverted my local copy.

[err.log.txt](https://github.com/angr/pyvex/files/764979/err.log.txt)
[out.log.txt](https://github.com/angr/pyvex/files/764980/out.log.txt)

**Comment by mattrepl** [comment]
And my compiler is the same version as @shelvenzhou's.

**Comment by f0rki** [comment]
Thanks @mattrepl Well it just seems like mac os is kind of broken... I don't know where that comes from, but it seems there are errors in the mac os provided header files. The generated pyvex header looks good though. 
I think we need to add a workaround. Can you do the same with with `clang -E -I../vex/pub pyvex_c/pyvex.h >out.log 2>err.log` and `clang++ -E -I../vex/pub pyvex_c/pyvex.h >out.log 2>err.log`.

and also `python2 -c 'import platform; print platform.system()'`

**Comment by mattrepl** [comment]
The string returned by `platform.system()` is `"Darwin"`. The clang error log is empty, the rest are attached.

[clang.out.log.txt](https://github.com/angr/pyvex/files/765142/clang.out.log.txt)
[clang++.err.log.txt](https://github.com/angr/pyvex/files/765140/clang.err.log.txt)
[clang++.out.log.txt](https://github.com/angr/pyvex/files/765141/clang.out.log.txt)

**Comment by f0rki** [comment]
perfect then using `clang -E` is what we actually want. Can you try with my branch again? 
Simple workaround: try `clang -E` first if `syst.platform() == 'Darwin'`

**Comment by mattrepl** [comment]
It works with one minor change. On line 63, when you insert `"clang"`, an index argument needs to be included.

**Comment by f0rki** [comment]
@mattrepl is simuvex working for you?

**Comment by mattrepl** [comment]
@f0rki I've been using VFG which relies on simuvex and haven't had any exceptions thrown. Is there something specific I should look for?

**Comment by mattrepl** [comment]
Also worth noting I run HEAD for most of the angr-related projects, including simuvex.
