### ISSUE TITLE
ArchARM translation issue

### ISSUE THREAD

**Issue by nimrodpar** [angr/pyvex#61]
When i translate:
```
SUB             R3, R11, #-var_18 4
MOV             R0, R3 4
LDR             R1, [R11,#var_14] 4
```
like so:
```
>>> import pyvex
>>> import archinfo
>>> arch = archinfo.ArchARM()
>>> i = pyvex.IRSB('\xe2K0\x18\xe1\xa0\x00\x03\xe5\x1b\x10\x14',0,arch)
>>> i.pp()
```
i get:
```
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I32 t5:Ity_I32 t6:Ity_I32 t7:Ity_I32 t8:Ity_I32 t9:Ity_I1 t10:Ity_I1 t11:Ity_I32 t12:Ity_I32 t13:Ity_I32 t14:Ity_I32 t15:Ity_I32 t16:Ity_I32 t17:Ity_I32 t18:Ity_I32 t19:Ity_I32 t20:Ity_I32 t21:Ity_I32 t22:Ity_I32 t23:Ity_I32 t24:Ity_I32 t25:Ity_I32 t26:Ity_I32 t27:Ity_I32 t28:Ity_I32

   00 | ------ IMark(0x0, 4, 0) ------
   01 | t4 = GET:I32(cc_op)
   02 | t3 = Or32(t4,0x00000010)
   03 | t5 = GET:I32(cc_dep1)
   04 | t6 = GET:I32(cc_dep2)
   05 | t7 = GET:I32(cc_ndep)
   06 | t8 = armg_calculate_condition(t3,t5,t6,t7):Ity_I32
   07 | t0 = t8
   08 | t10 = 32to1(t0)
   09 | t9 = Not1(t10)
   10 | if (t9) { PUT(pc) = 0x4; Ijk_Boring }
   11 | t1 = GET:I32(r0)
   12 | t2 = t1
   13 | t11 = Sub32(t1,0x00000020)
   14 | PUT(r0) = t11
   15 | t13 = Sub32(t2,0x00000000)
   16 | t12 = LDle:I32(t13)
   17 | PUT(lr) = t12
   18 | t15 = Sub32(t2,0x00000004)
   19 | t14 = LDle:I32(t15)
   20 | PUT(r11) = t14
   21 | t17 = Sub32(t2,0x00000008)
   22 | t16 = LDle:I32(t17)
   23 | PUT(r9) = t16
   24 | t19 = Sub32(t2,0x0000000c)
   25 | t18 = LDle:I32(t19)
   26 | PUT(r8) = t18
   27 | t21 = Sub32(t2,0x00000010)
   28 | t20 = LDle:I32(t21)
   29 | PUT(r7) = t20
   30 | t23 = Sub32(t2,0x00000014)
   31 | t22 = LDle:I32(t23)
   32 | PUT(r6) = t22
   33 | t25 = Sub32(t2,0x00000018)
   34 | t24 = LDle:I32(t25)
   35 | PUT(r5) = t24
   36 | t27 = Sub32(t2,0x0000001c)
   37 | t26 = LDle:I32(t27)
   38 | PUT(r1) = t26
   39 | PUT(ip) = 0x00000004
   40 | t28 = GET:I32(ip)
   NEXT: PUT(pc) = t28; Ijk_Boring
}
```
Which seems completely unrelated, and misses the fact that there are 3 instructions. The asm and bytes were extracted with IDA.

**Comment by rhelmot** [comment]
The problem is that your bytes are for big-endian arm, and the default archinfo arm arch is little-endian, I think. If you set `traceflags=-1` in the IRSB constructor, VEX dumps out a ton of info, including its dissasembly of the instructions as it's lifting them. It thinks your first instruction is `ldmda{ne} r0!, {0x4be2}`. The conditional part of this instruction also causes pyvex to cut the basic block short.

**Comment by rhelmot** [comment]
You can fix this by passing `'Iend_LE'` as a the first parameter to the ArchARM constructor.

**Comment by nimrodpar** [comment]
Awesome thanks!

**Comment by nimrodpar** [comment]
So when i try translating the following ARMEL command in thumb mode:
`MOV             R9, R1 2`
Using: 
`pyvex.IRSB(raw_bytes, address, arch, num_bytes=2, traceflags=-1)`
(address=`0x298d7` and raw_bytes=`0x89 0x46` and ARMEL arch)

I get this:
```
------------------------ Front end ------------------------

	(thumb) 0x298d6:  ldrh r5, [r7, #8]

              ------ IMark(0x298d6, 2, 1) ------
              t0 = GET:I32(392)
              t1 = Shr32(t0,0x8:I8)
              PUT(392) = t1
              t2 = armg_calculate_condition[mcx=0x9]{0x7f718691ae50}(Or32(GET:I32(72),Xor32(And32(t0,0xf0:I32),0xe0:I32)),GET:I32(76),GET:I32(80),GET:I32(84)):I32
              t3 = ITE(CmpNE32(And32(t0,0xf0:I32),0x0:I32),t2,0x1:I32)
              t4 = Xor32(And32(t0,0x1:I32),0x1:I32)
              t5 = And32(t4,t3)
              PUT(392) = t0
              t6 = if-strict (CmpNE32(t3,0x0:I32)) 16Uto32(LDle(Add32(GET:I32(36),0x8:I32))) else GET:I32(28)
              PUT(28) = t6
              PUT(392) = t1
              PUT(68) = 0x298d9:I32

	(thumb) 0x298d8:  lsls r6, r0, #1

              ------ IMark(0x298d8, 2, 1) ------
              t7 = GET:I32(392)
              t8 = Shr32(t7,0x8:I8)
              PUT(392) = t8
              t9 = armg_calculate_condition[mcx=0x9]{0x7f718691ae50}(Or32(GET:I32(72),Xor32(And32(t7,0xf0:I32),0xe0:I32)),GET:I32(76),GET:I32(80),GET:I32(84)):I32
              t10 = ITE(CmpNE32(And32(t7,0xf0:I32),0x0:I32),t9,0x1:I32)
              t11 = Xor32(And32(t7,0x1:I32),0x1:I32)
              t12 = And32(t11,t10)
              t15 = GET:I32(8)
              t16 = armg_calculate_flag_v[mcx=0x9]{0x7f718691ac10}(GET:I32(72),GET:I32(76),GET:I32(80),GET:I32(84)):I32
              t14 = And32(Shr32(t15,0x1f:I8),0x1:I32)
              t13 = Shl32(t15,0x1:I8)
              PUT(32) = ITE(CmpNE32(t10,0x0:I32),t13,GET:I32(32))
              t17 = CmpNE32(t12,0x0:I32)
              PUT(72) = ITE(t17,0x5:I32,GET:I32(72))
              PUT(76) = ITE(t17,t13,GET:I32(76))
              PUT(80) = ITE(t17,t14,GET:I32(80))
              PUT(84) = ITE(t17,t16,GET:I32(84))
              PUT(68) = 0x298db:I32
...
```

Which shows that the instruction was interpreted as `ldrh r5, [r7, #8]` (and for some reason more than 1 instruction is lifted..)

I got the original command from IDA. Any feedback would be most welcome :pray:

**Comment by rhelmot** [comment]
You need to specify `bytes_offset=1` (iirc) in order to let the lifter know that the address you provided corresponds to the one byte into the string you provided!

**Comment by zardus** [comment]
Maybe we should add a `thumb` kwarg that automatically adjusts the address
and byte_offset when people want to do this manually?

On Apr 15, 2017 2:02 PM, "Andrew Dutcher" <notifications@github.com> wrote:

You need to specify bytes_offset=1 (iirc) in order to let the lifter know
that the address you provided corresponds to the one byte into the string
you provided!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/angr/pyvex/issues/61#issuecomment-294317640>, or mute
the thread

**Comment by rhelmot** [comment]
This is already a thing in angr. should we push it all the way down into pyvex?

**Comment by nimrodpar** [comment]
I'm probably missing something here, but why would i specify `bytes_offset=1`if `raw_bytes` holds just the 2 bytes of the command? wouldn't specifying that mean that the command is just the last `0x46` byte? (not to mention that i tried that and it doesn't work :|).

I think adding an argument for thumb mode would be great, since its not very clear how to use it, and we (and i think many others) use angr at the pyvex level directly.

For now, if you could just tell how to call the IRSB c'tor to translate the thumb mode inst at `address=0x298d6` and `raw_bytes="{}{}".format(chr(0x89),chr(0x46))`, maybe it would make things clear. Much obliged!

**Comment by rhelmot** [comment]
```
In [5]: pyvex.IRSB('\x89\x46', 0x298d7, archinfo.ArchARMEL(), bytes_offset=1, traceflags=-1)
[15:57:14] [pyvex.lift.libvex]       |     INFO: 
------------------------ Front end ------------------------

        (thumb) 0x298D6:  mov r9, r1
```

You have to do this to specify that there is a discrepancy between the start of the bytes you've provided and the address you've provided. Without it, pyvex will assume that 0x89 is the byte in memory at address 0x298d7. By providing bytes_offset, it will understand that 0x89 is actually the value in memory at address 0x298d6.

**Comment by rhelmot** [comment]
I just realized now that my previous explanation of the need for bytes_offset was backward, please disregard it :)

**Comment by rhelmot** [comment]
...previous explanation as in the one from two days ago, not the most recent one. sorry

**Comment by nimrodpar** [comment]
Cool, got it. 

One last thing: I tried translating 4-bytes-long instructions in thumb mode, for example:
`0x298c8 PUSH.W          {R0-R2,R4-R11,LR}` (the raw bytes are `'\x2d\xe9\xf7\x4f'`)
But i just get an empty block:
```
IRSB {
   t0:Ity_I32 t1:Ity_I32 t2:Ity_I32 t3:Ity_I32 t4:Ity_I32 t5:Ity_I32 t6:Ity_I32 t7:Ity_I32

   00 | ------ IMark(0x298c8, 0, 0) ------
   NEXT: PUT(pc) = 0x000298c8; Ijk_NoDecode
}
```
I guess its not well-supported? (understandably..)

p.s. In case you're keeping track, or not :), we added a citation and ack for angr in our [recent PLDI17 paper](http://pldi17.sigplan.org/event/pldi-2017-papers-similarity-of-binaries-through-re-optimization). Cheers for all the good work.

**Comment by rhelmot** [comment]
The same approach works: `pyvex.IRSB('\x2d\xe9\xf7\x4f', 0x298c9, archinfo.ArchARMEL(), bytes_offset=1)`. VEX will call this instruction `stmdb r13!, {0x4FF7}`, but it's the same as what IDA calls your PUSH.W instruction. The VEX disassembly printer is meant to be cheap.

In general, VEX has extremely good instruction set coverage, better than pretty much any other IR, since Valgrind has to be able to lift any code it analyzes.

**Comment by nimrodpar** [comment]
Got it

**Comment by nimrodpar** [comment]
`pyvex.IRSB('\x4f\xea', 0x29901, archinfo.ArchARMEL(), bytes_offset=1)` (thumb mode `LSRS            R5, R4, #0x10`) gets
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyvex/block.py", line 64, in __init__
    lift(self, data, max_bytes, max_inst, bytes_offset, opt_level, traceflags)
  File "/usr/local/lib/python2.7/dist-packages/pyvex/lift/__init__.py", line 100, in lift
    raise PyVEXError('\n\n'.join(errors))
pyvex.errors.PyVEXError: 
vex: priv/guest_generic_bb_to_IR.c:439 (bb_to_IR): Assertion `st->tag == Ist_Put' failed.
```

on latest angr

**Comment by rhelmot** [comment]
Shit. That's a bug in vex, possibly to our patches to vex. Will look into this.

**Comment by rhelmot** [comment]
Ok, so it looks like that's not actually the bytecode for `LSRS R5,R4, #0x10`. [ODA](https://www.onlinedisassembler.com/odaweb/) refuses to disassemble 4F EA for me unless I add two zeros on the end of it, and then it says it's a `mov.w r0, r0`. VEX seems to agree with me here, so what happens is that it disassembles the mov.w, and then sees that it's gone over the byte limit (4 bytes instead of the 2 provided) and tries to roll back. However, there is nothing to roll back to, so it dies.
