### ISSUE TITLE
vex: priv/guest_arm_toIR.c:14699 (disInstr_ARM_WRK): Assertion `0 == (guest_R15_curr_instr_notENC & 3)' failed

### ISSUE THREAD

**Issue by nimrodpar** [angr/pyvex#62]
I get a `vex: priv/guest_arm_toIR.c:14699 (disInstr_ARM_WRK): Assertion '0 == (guest_R15_curr_instr_notENC & 3)' failed` error when trying to translate:
```
0x62 MOVS            R0, R0 2
0x64 LSLS            R4, R7, #7 2
0x66 MOVS            R0, R0 2
0x68 LSLS            R4, R3, #8 2
0x6a MOVS            R0, R0 2
0x6c MOVS            R6, R0 2
0x6e MOVS            R0, R0 2
0x70 STRH            R0, [R0] 2 
```
Any thoughts?

**Comment by rhelmot** [comment]
If you are trying to disassembly thumb code, you need to pass in an odd address. There is no way to distinguish between arm and thumb code with just an address normally, since it's a separate processor flag. libVEX gets around this by using the lowest bit in the address to represent the thumb bit.

**Comment by nimrodpar** [comment]
gotcha, thanks!
