### ISSUE TITLE
pyvex OSX build failed

### ISSUE THREAD

**Issue by fr0zenrain** [angr/pyvex#65]
pyvex's version is so confuse,i'm be crazy!

error: no member named 'arm64_allow_reordered_writeback' in 'VexControl'
        vc.arm64_allow_reordered_writeback = 0;

**Comment by rhelmot** [comment]
This is a version mismatch bug. Your pyvex is newer than your VEX. If you're installed from several cloned repositoires, you will need to be careful, since we force-pushed to VEX recently.

**Comment by fr0zenrain** [comment]
it's ok,i manual redownload vex-mater.zip to my pyvex directory.
