### ISSUE TITLE
X86 address  override '67h' prefix with `AND` instruction invokes sanity check fail

### ISSUE THREAD

**Issue by kye4u2** [angr/pyvex#80]
Generating an irsb for the following AMD64 opcode `67 20 74 6F ` yields the following pyvex error:
pyvex.errors.PyVEXError: sanityCheckFail: exiting due to bad IR

`irsb = pyvex.IRSB("\x67\x20\x74\x6F", 0x400400, archinfo.ArchX86(), num_inst=1, num_bytes=4)`

yields

> irsb = pyvex.IRSB("\x67\x20\x74\x6F", 0x400400, archinfo.ArchX86(), num_inst=1, num_bytes=4)
  File "/targaryen/targaryen/env/angr-dev/pyvex/pyvex/block.py", line 60, in __init__
    lift(self, data, num_bytes, num_inst, bytes_offset, traceflags)
  File "/targaryen/targaryen/env/angr-dev/pyvex/pyvex/lift/__init__.py", line 88, in lift
    raise PyVEXError('\n\n'.join(errors))
pyvex.errors.PyVEXError: sanityCheckFail: exiting due to bad IR

Based on independent sources, the opcode should decode to `and     [si+6Fh], dh`

It appears there may be an issue with the handling of the address override prefix `67h`

**Comment by kye4u2** [comment]
Just realized that I need the archinfo to be AMD64...

**Comment by rhelmot** [comment]
This was fixed here I believe: https://github.com/angr/vex/commit/de57079896ab8857a9bece086dd9663eb1e5c3f6
