### ISSUE TITLE
pip install SSL: CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by squizz617** [angr/pyvex#88]
`pip install pyvex` fails on ubuntu 16.04, with the following error message.
```
$ pip install pyvex
Collecting pyvex
  Using cached pyvex-6.7.7.27.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-FBZebn/pyvex/setup.py", line 41, in <module>
        v.write(urllib2.urlopen(VEX_URL).read())
      File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python2.7/urllib2.py", line 429, in open
        response = self._open(req, data)
      File "/usr/lib/python2.7/urllib2.py", line 447, in _open
        '_open', req)
      File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
        result = func(*args)
      File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
        context=self._context)
      File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-FBZebn/pyvex/
```
[HERE](https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi) it suggests that `pip install --trusted-host HOSTNAME` will resolve the issue, but `pip install --trusted-host pypi.python.org pyvex` also failed.
A fix or suggestion will be appreciated!

**Comment by ltfish** [comment]
Try specifying "github.com" instead of "pypi.python.org" for the trusted host.

**Comment by squizz617** [comment]
Tried that as well, but got the same error.

**Comment by rhelmot** [comment]
The error has to do with the fact that we manually download the vex sources from github, so passing an option to pip won't do much. There's probably something messed up with your root CA, as I'm unable to reproduce this on my own 16.04 machine.

If there's a way to detect that `--trusted-host` was passed to pip we could use that, but we should probably just fix https://github.com/angr/vex/issues/7 which will fix this.

**Comment by rhelmot** [comment]
https://github.com/angr/pyvex/commit/fa1e969ede02b8a2420fdb907036136ff1feb63c will fix this, as soon as we make a new release!
