### ISSUE TITLE
Spotters: Lifters that help other lifters when they fail (using Gymrat)

### ISSUE THREAD

**Issue by subwire** [angr/pyvex#91]
This is a tracking issue for the effort to implement "Spotters" -- lifters that fix-up or implement missing features in other lifters.

The primary goal of this in the short term is to add hot-patches to libVEX using the gymrat framework, as we expect this to be 100000x easier than modding VEX itself.
For example, let's say we want to implement `svc` in ARM Cortex M; I don't expect the VEX folks to ever want to do that.  So we'll do it! But modding libVEX is complex, and I don't want to write a full gymrat lifter for ARM.  A Spotter here would be perfect.
 
Some scratch ideas:
- Lifters in pyvex are registered in "order", and tried in order, and if they fail, keep trying them
- rhelmot says we should be able to get partial blocks from VEX. This is the crucial trick.

Tasks:
1. Merge `feature/expanded_reality` into master so gymrat actually works
2. Mod the primary lifter mechanism so that partial block info is available to future lifters
3. Create a `Spotter` class (in lifter_helper.py) appropriate for these sorts of lifters.
4. Success criteria: We can do Cortex M4 hard FPU and maybe SVC, etc instructions this way.

**Comment by subwire** [comment]
CC @tyb0807

**Comment by tyb0807** [comment]
Thanks @subwire. I think I can help you on this. Or at least on svc and exceptions handling (not sure about the fpu though).

But first of all, how can I roughly have an idea of what is exactly gymrat? What is the idea of expanded reality?

Furthermore, in order to correctly handle svc, some special purpose registers need to be added. Where would they fit in? I put them temporarily in archinfo, but zardus said that it should be in angr-platforms.

**Comment by Nilocunger** [comment]
Gymrat is a framework for creating new lifters for angr. It provides nice syntax for writing the vex that instructions translate into and automates a bunch of the infrastructure necessary for a lifter. For an example of such a lifter, see [here](https://github.com/angr/angr-platforms/blob/master/angr_platforms/msp430/instrs_msp430.py). 

Expanded reality is a branch devoted to removing angr's reliance on a byte being 8 bits (see the cLEMENCy architecture). 

In terms of spotters, I've gotten started on implementing them. It appears that when Vex fails to decode an instruction, it returns the partial block with a jumpkind of Ijk_NoDecode. I currently detect when an instruction has failed to decode using the jumpkind and then try all of the other lifters (in true angr style) until one works, and then concatenate all of the blocks together. I should have that finished off and working by tonight or tomorrow. At that point we will need a lifter for these instructions and some test cases with the svc instruction.

**Comment by tyb0807** [comment]
I have a test case (FreeRTOS) but compiled for Cortex-M3. Btw, have you implemented `cps`, `msr` and `mrs` instructions as well?

Thanks for the explanation. So basically what should I do to help you?

**Comment by subwire** [comment]
Implemented in PR#104
