### ISSUE TITLE
Incorrect handling of rep stosd

### ISSUE THREAD

**Issue by davidtr1037** [angr/pyvex#96]
In some cases, when trying to lift a basic block which contains a *rep stosd* instruction, we get a wrong translation.
For example, when trying to lift "\xb8\xcc\xcc\xcc\xcc\xf3\xab":
```
mov eax, 0xcccccccc
rep stosd
```
we get:
```
00 | ------ IMark(0x0, 5, 0) ------
   01 | PUT(eax) = 0xcccccccc
   02 | PUT(eip) = 0x00000005
   03 | ------ IMark(0x5, 2, 0) ------
   04 | t1 = GET:I32(ecx)
   05 | t4 = CmpEQ32(t1,0x00000000)
   06 | if (t4) { PUT(eip) = 0x7; Ijk_Boring }
   07 | t5 = Sub32(t1,0x00000001)
   08 | PUT(ecx) = t5
   09 | t7 = GET:I32(dflag)
   10 | t6 = Shl32(t7,0x02)
   11 | t3 = GET:I32(edi)
   12 | STle(t3) = 0xcccccccc
   13 | t8 = Add32(t3,t6)
   14 | PUT(edi) = t8
   NEXT: PUT(eip) = 0x00000005; Ijk_Boring
```
But when trying to lift "\xb9\x04\x00\x00\x00\xb8\xcc\xcc\xcc\xcc\xf3\xab":
```
mov ecx, 4
mov eax, 0xcccccccc
rep stosd
```
we get:
```
   00 | ------ IMark(0x0, 5, 0) ------
   01 | PUT(ecx) = 0x00000004
   02 | ------ IMark(0x5, 5, 0) ------
   03 | PUT(eax) = 0xcccccccc
   04 | PUT(eip) = 0x0000000a
   05 | ------ IMark(0xa, 2, 0) ------
   06 | PUT(ecx) = 0x00000003
   07 | t7 = GET:I32(dflag)
   08 | t6 = Shl32(t7,0x02)
   09 | t3 = GET:I32(edi)
   10 | STle(t3) = 0xcccccccc
   11 | t8 = Add32(t3,t6)
   12 | PUT(edi) = t8
   NEXT: PUT(eip) = 0x0000000a; Ijk_Boring
```

The first translation seems to be the correct one.
Do you have any idea why the second translation works differently?

The code is lifted using:
```py
pyvex.IRSB(<code>, 0, archinfo.ArchX86())
```

**Comment by ltfish** [comment]
Both translations look correct to me. Can you please explain why the second one is incorrect?

You might want to turn off the IRSB optimization (`pyvex.IRSB(..., opt_level=0)`) to get the "correct" one.

**Comment by davidtr1037** [comment]
The second one looks like an infinite loop.
I would expect from it to jump to the next instruction once *ecx* is zero.

**Comment by rhelmot** [comment]
The second one is, as fish describes, the result of vex's optimization. The first time you run through that loop, it is impossible to break out of the loop since we know the value of ecx. When we jump backwards, the block will be re-lifted starting from the midpoint and it will include the conditional branch. If you want IR that is usable from all points, turn off optimization.

**Comment by davidtr1037** [comment]
I see it now. Thanks!

**Comment by davidtr1037** [comment]
By the way, is there a way to avoid conditional branches in a *middle* of a block?
It will make static analysis easier...

**Comment by ltfish** [comment]
> By the way, is there a way to avoid conditional branches in a middle of a block?

Can you give me an example?

I assume you want to use a "normalized" CFG. You should use angr's CFG for this (with `normalized=True`).

**Comment by davidtr1037** [comment]
For example, the block from above:
```
   00 | ------ IMark(0x0, 5, 0) ------
   01 | PUT(eax) = 0xcccccccc
   02 | PUT(eip) = 0x00000005
   03 | ------ IMark(0x5, 2, 0) ------
   04 | t1 = GET:I32(ecx)
   05 | t4 = CmpEQ32(t1,0x00000000)
   06 | if (t4) { PUT(eip) = 0x7; Ijk_Boring }
   07 | t5 = Sub32(t1,0x00000001)
   08 | PUT(ecx) = t5
   09 | t7 = GET:I32(dflag)
   10 | t6 = Shl32(t7,0x02)
   11 | t3 = GET:I32(edi)
   12 | STle(t3) = 0xcccccccc
   13 | t8 = Add32(t3,t6)
   14 | PUT(edi) = t8
   NEXT: PUT(eip) = 0x00000005; Ijk_Boring
```
which contains a conditional branch in the middle of the block.

**Comment by ltfish** [comment]
Create a "normalized" CFG will give you blocks that do not contain branches jumping to the middle of existing blocks.
