### ISSUE TITLE
How to get Vex-IR for an entire function?

### ISSUE THREAD

**Issue by buptsseGJ** [angr/pyvex#97]
I want to do such a thing: convert an function to IR. But just using pyvex doesn't seem to work. I provided
all  the hexadecimal opcodes of a entire function to pyvex.IRSB, for example:
```
        irsb1 = pyvex.IRSB(data=(
                            '\x8B\x45\x08'
                            '\x83\xE0\x01'
                            '\x89\x45\xF4'
                            '\x83\x7D\xF4\x00'
                            '\x74\x13'
                            '\x8B\x45\x08'
                            '\x89\x44\x24\x04'
                            '\xC7\x04\x24\x10\x85\x04\x08'
                            '\xE8\xA5\xFE\xFF\xFF'
                            '\x90'
                            '\xC9'
                            '\xC3'),
                           mem_addr=0x08048429,arch=archinfo.ArchX86())
```
The result of IR only contains the first baisc block of the function which starts address is 0x08048429.
If I convert every basic block to IR, I need to merge these IRs into a entire IR for a function. But there is a problem in which the block-level IRs produces variable conflicts(eg. multiple block-level IRs contains temporary variable t2). How can I get Vex-IR for an entire function conveniently and correctly?

**Comment by ltfish** [comment]
Please consider using angr. For example, angr's `CFGFast` does this for you.

**Comment by buptsseGJ** [comment]
Thank you very much for answering my issue. I tried the `CFGFast()` via `proj.analyses.CFGFast()`, then I can get all the nodes for a function. It use a similar way(eg. `proj.factory.block(0x804841d)`) as pyvex to convert a block into IR. But I still cannot get an entire IR **for a function** through **sevaral API calls**. Is there any existing method to fulfill this requirement? It seems that we also need to convert IR for each node `cfg.get_any_node(0x804841d)`. Thanks.

**Comment by rhelmot** [comment]
The VEX IR is not able to represent an entire function. It is not designed
for this.

**Comment by yuedeji** [comment]
Just curious, did you get any luck to get a function's IR later?

**Comment by rhelmot** [comment]
the previous comments still apply. VEX is not designed to represent a whole function.

**Comment by yuedeji** [comment]
I see, thanks. I'm new to angr, I'm just wondering do you have any example programs to iterate all the blocks in function and translate them to IRs?

**Comment by rhelmot** [comment]
This is a control-flow recovery task - you want to run a CFG analysis (`project.analysis.CFGFast()`, you can tweak the arguments to limit the scope) and then the knowledge base will have function information available as `project.kb.functions`.

**Comment by rhelmot** [comment]
I guess it's a low level IR? I'm not familiar with the terminology you're using.

that question seems to only makes sense in the context of compiler IRs. VEX is a lifter IR, where the goal is first and foremost to represent the semantics of binary code under a CPU. There is an optimization setting you can specify, but because of the goals of the IR (represent the semantics of a block of code), they are very limited in scope and can't do much besides redundant operation elimination and constant propagation.

Please open a new issue if you have more questions.

**Comment by yuedeji** [comment]
All right, thanks!
