### ISSUE TITLE
The relationship between arch.memory_endness and instructions

### ISSUE THREAD

**Issue by ltfish** [angr/pyvex#99]
Here is a snippet from `lift/util/instr_helper.py`:

```
        if self.arch.memory_endness == 'Iend_LE':
            # Get it out little endian.  I hate this.
            instr_bits = bitstring.Bits(uint=bitstrm.peek("uintle:%d" % numbits), length=numbits).bin
        else:
            instr_bits = bitstrm.peek("bin:%d" % numbits)
```

It seems that when memory_endness is little endian, the bytes of an instruction is reversed. I don't think this is the case for any architecture with a little endian memory. IMO the memory endianness has nothing to do with the order of how instruction bytes are stored. It only controls how bytes of words are stored on the architecture.

Thoughts?

**Comment by ltfish** [comment]
@zardus @rhelmot Thoughts?

**Comment by zardus** [comment]
I am fine with either solution. In the case of a variable-length ISA, it doesn't make sense to correct for endness in the instructions. For others, my guess is that it still doesn't make sense, but I could be wrong.

TBH, this seems like a minor deal, design-wise. I'm fine with whatever solution is convenient.

**Comment by subwire** [comment]
So, this has less to do with the actual endness of memory and more to do with the endness of the instruction format.  We copied all of the instruction formats out of the MSP430 ISA as-written, only to find that the actual instructions were stored in memory endy-flipped! Gah! 
We want people to be able to describe the format as naturally as possible, so being able to correct for this at the lifter is pretty convenient.  The only question is where that option should be stored

That may be some minor part of the more major question about the future of archinfo... but for now, will an elegant hack work? Like "instruction_endness"? (which defaults to something sane)

**Comment by zardus** [comment]
`instruction_endness` makes sense to me.

**Comment by subwire** [comment]
Done!
